# Generated by Django 2.2.6 on 2019-11-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(blank=True, max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_freelancer', models.IntegerField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Budgets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budgettype_id', models.IntegerField()),
                ('currency_id', models.IntegerField()),
                ('min', models.IntegerField(default=None)),
                ('max', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updates_at')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_type', models.CharField(default=None, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updates_at')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=50)),
                ('categorycode', models.CharField(default=None, max_length=60, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=30, unique=True)),
                ('country_name', models.CharField(max_length=30, unique=True)),
                ('country_phone', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updates_at')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencytype', models.CharField(max_length=30)),
                ('currencysymbol', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updates_at')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('profilepic', models.ImageField(upload_to='pictures/')),
                ('current_ongoing_jobs', models.CharField(max_length=40)),
                ('completed_recent_projects', models.CharField(max_length=40)),
                ('recommended_jobs', models.CharField(max_length=40)),
                ('wallet', models.IntegerField()),
                ('feedback_reviews', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='KycInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=None, null=True)),
                ('fullname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('mobile', models.CharField(max_length=17)),
                ('idprooffront', models.ImageField(upload_to='pictures/')),
                ('idproofback', models.ImageField(upload_to='pictures/')),
                ('kycstatus', models.IntegerField(null=True)),
                ('username', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(blank=True, max_length=60)),
                ('subcategory_id', models.CharField(blank=True, max_length=60)),
                ('projecttitle', models.CharField(max_length=50)),
                ('route', models.CharField(blank=True, max_length=100, unique=True)),
                ('projectcode', models.CharField(default=None, max_length=30, null=True, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('files', models.FileField(upload_to='pictures/files/')),
                ('userid', models.IntegerField(default=None, null=True)),
                ('username', models.CharField(default=None, max_length=50, null=True)),
                ('skills', models.TextField(max_length=300)),
                ('budgetTypeId', models.IntegerField(default=None)),
                ('currencyid', models.IntegerField(default=None)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('custombudget', models.IntegerField()),
                ('projectdeadline', models.DateField()),
                ('experiencerequired', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(default=None)),
                ('skills', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(default=None)),
                ('subcategoryname', models.CharField(max_length=60)),
                ('subcategorycode', models.CharField(default=None, max_length=60, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('userid', models.IntegerField(default=None, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('skills', models.TextField()),
                ('profile', models.ImageField(upload_to='pictures/')),
                ('coverphoto', models.ImageField(upload_to='pictures/')),
                ('country', models.CharField(max_length=30)),
            ],
        ),
    ]
