# Generated by Django 2.2.6 on 2019-11-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(blank=True, default=None)),
                ('project_code', models.CharField(default=None, max_length=30, null=True)),
                ('project_name', models.CharField(default=None, max_length=300, null=True)),
                ('bid_amount', models.IntegerField()),
                ('user_id', models.IntegerField(default=None, null=True)),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('no_of_bid', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Const_skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updates_at')),
            ],
        ),
        migrations.CreateModel(
            name='No_of_bids_for_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(default=None, max_length=30, null=True)),
                ('project_name', models.CharField(default=None, max_length=300, null=True)),
                ('no_of_bid', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updates_at')),
            ],
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='categorycode',
            new_name='category_code',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='categoryname',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='currencysymbol',
            new_name='currency_symbol',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='currencytype',
            new_name='currency_type',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='profilepic',
            new_name='profile_pic',
        ),
        migrations.RenameField(
            model_name='postproject',
            old_name='budgetTypeId',
            new_name='budgetType_Id',
        ),
        migrations.RenameField(
            model_name='postproject',
            old_name='country',
            new_name='country_id',
        ),
        migrations.RenameField(
            model_name='postproject',
            old_name='currencyid',
            new_name='currency_id',
        ),
        migrations.RenameField(
            model_name='postproject',
            old_name='custombudget',
            new_name='custom_budget',
        ),
        migrations.RenameField(
            model_name='postproject',
            old_name='experiencerequired',
            new_name='experience_required',
        ),
        migrations.RenameField(
            model_name='postproject',
            old_name='projectcode',
            new_name='project_code',
        ),
        migrations.RenameField(
            model_name='postproject',
            old_name='projectdeadline',
            new_name='project_deadline',
        ),
        migrations.RenameField(
            model_name='postproject',
            old_name='projecttitle',
            new_name='project_title',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcategorycode',
            new_name='sub_category_code',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcategoryname',
            new_name='sub_category_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='country',
            new_name='country_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='coverphoto',
            new_name='cover_photo',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='userid',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='postproject',
            name='skill1',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='postproject',
            name='skill2',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='postproject',
            name='skill3',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='postproject',
            name='route',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='skills',
            name='category_id',
            field=models.IntegerField(blank=True),
        ),
    ]
