# Generated by Django 2.2.6 on 2019-11-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191121_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='postproject',
            name='skill4',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
