# Generated by Django 2.2.6 on 2019-11-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_postproject_skill4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Json_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillcode', models.CharField(max_length=30)),
            ],
        ),
    ]
