# Generated by Django 2.2.6 on 2019-11-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191122_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skill_name',
        ),
    ]
