# Generated by Django 2.2.6 on 2019-11-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20191122_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill_code',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
