# Generated by Django 2.2.6 on 2019-11-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20191122_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='const_skills',
            name='skill_code',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
