# Generated by Django 2.2.6 on 2019-11-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_skills_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='const_skills',
            name='category_id',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
