# Generated by Django 2.2.6 on 2019-12-16 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_const_skills_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exp_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Phone_OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='phone number must be entered in sollowing way', regex='\\+?1?\\d{9,14}$')])),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('count', models.IntegerField(default=0, help_text='number of otp sent')),
            ],
        ),
        migrations.AddField(
            model_name='bidproject',
            name='completion_time',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='postproject',
            name='custom_budget',
            field=models.IntegerField(null=True),
        ),
    ]
