# Generated by Django 2.2.6 on 2019-12-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20191216_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidproject',
            name='completion_time',
        ),
    ]
