# Generated by Django 2.2.6 on 2019-12-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_bidproject_completion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidproject',
            name='completion_time',
            field=models.TextField(default=None, max_length=300),
        ),
    ]
