# Generated by Django 2.2.6 on 2019-12-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_bidproject_completion_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hirer_bid_select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hirer_email_id', models.EmailField(max_length=254)),
                ('project_id', models.IntegerField()),
                ('freelancer_email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
