# Generated by Django 2.2.6 on 2019-12-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_hirer_bid_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirer_bid_select',
            name='project_route',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
