# Generated by Django 2.2.6 on 2019-12-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20191218_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidproject',
            name='contact_no',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bidproject',
            name='descreption',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
