# Generated by Django 2.2.6 on 2019-12-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20191223_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidproject',
            name='contact_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='kycinfo',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
