# Generated by Django 2.2.6 on 2019-12-23 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20191223_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidproject',
            name='contact_no',
        ),
    ]
