# Generated by Django 2.2.6 on 2019-12-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_remove_bidproject_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True)),
                ('skill_name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='country_id',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='skills',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hourely_rate',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portfolio',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidproject',
            name='email',
            field=models.EmailField(max_length=60, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
