# Generated by Django 2.2.6 on 2019-12-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20191223_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproject',
            name='category_id',
            field=models.IntegerField(blank=True, max_length=60),
        ),
    ]
