# Generated by Django 2.2.6 on 2019-12-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20191224_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproject',
            name='category_id',
            field=models.IntegerField(blank=True),
        ),
    ]
