# Generated by Django 2.2.6 on 2019-12-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20191224_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='countryname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
