# Generated by Django 2.2.6 on 2020-01-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20191224_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='countryname',
        ),
        migrations.AddField(
            model_name='user_skills',
            name='skill_id',
            field=models.IntegerField(default=None),
        ),
    ]
