# Generated by Django 2.2.6 on 2020-01-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_userprofile_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bid_count',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='portfolio',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
