# Generated by Django 2.2.6 on 2020-01-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_auto_20200103_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bid',
            field=models.IntegerField(default=False),
        ),
    ]
