# Generated by Django 2.2.6 on 2020-01-07 06:31

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_const_languages_user_languages_userportfolioprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', jsonfield.fields.JSONField()),
            ],
        ),
    ]
