# Generated by Django 2.2.6 on 2020-01-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_test_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bid_count',
        ),
    ]
