# Generated by Django 2.2.6 on 2020-01-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_remove_userprofile_bid_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproject',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='postproject',
            name='project_title',
            field=models.CharField(max_length=30),
        ),
    ]
