# Generated by Django 2.2.6 on 2020-01-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_auto_20200109_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_languages',
            name='language_name',
            field=models.CharField(max_length=300),
        ),
    ]
