# Generated by Django 2.2.6 on 2020-01-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_auto_20200109_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_languages',
            name='language_name',
        ),
    ]
