# Generated by Django 2.2.6 on 2020-01-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_remove_test_languages_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycinfo',
            name='idprooffront',
            field=models.ImageField(default='http://3.9.164.7:8000/media/yonghyun-lee-RhGK4qOwxxw-unsplash.jpg', upload_to=''),
        ),
    ]
