# Generated by Django 2.2.6 on 2020-01-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_auto_20200110_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycinfo',
            name='idprooffront',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(default='yonghyun-lee-RhGK4qOwxxw-unsplash.jpg', upload_to=''),
        ),
    ]
