# Generated by Django 2.2.6 on 2020-01-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_auto_20200110_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproject',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='postproject',
            name='project_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(max_length=300),
        ),
    ]
