# Generated by Django 2.2.6 on 2020-01-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_auto_20200113_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaiseTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('tickettype', models.IntegerField()),
                ('user_id', models.IntegerField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updates_at')),
            ],
        ),
        migrations.CreateModel(
            name='TicketCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
