# Generated by Django 2.2.6 on 2020-01-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_raiseticket_ticketcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproject',
            name='description',
            field=models.TextField(),
        ),
    ]
