# Generated by Django 2.2.6 on 2020-01-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_auto_20200115_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolioprofile',
            name='project_images',
            field=models.FileField(upload_to=''),
        ),
    ]
