# Generated by Django 2.2.6 on 2020-01-21 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_auto_20200115_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kycinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updates_at'),
        ),
    ]
