# Generated by Django 2.2.6 on 2020-01-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_auto_20200121_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_image',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
