# Generated by Django 2.2.6 on 2020-01-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_account_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=True, related_name='user', to='account.UserPortfolioProfile')),
            ],
        ),
    ]
