# Generated by Django 2.2.6 on 2020-01-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0058_portfolioimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioimages',
            name='user',
        ),
        migrations.AddField(
            model_name='portfolioimages',
            name='userid',
            field=models.IntegerField(default=None),
        ),
    ]
