# Generated by Django 2.2.6 on 2020-01-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0059_auto_20200129_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='postproject',
            name='project_status',
            field=models.IntegerField(default=None),
        ),
    ]
