# Generated by Django 2.2.6 on 2020-01-30 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_postproject_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(default='yonghyun-lee-RhGK4qOwxxw-unsplash.jpg', upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'png', 'gif'])]),
        ),
    ]
