# Generated by Django 2.2.6 on 2020-02-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidproject',
            name='bid_status',
            field=models.IntegerField(default=None),
        ),
    ]
