# Generated by Django 2.2.6 on 2020-02-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0064_auto_20200203_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproject',
            name='budgetType_Id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
