# Generated by Django 2.2.6 on 2020-02-10 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0065_auto_20200210_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.ImageField(default='yonghyun-lee-RhGK4qOwxxw-unsplash.jpg', upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'png', 'gif'])]),
        ),
    ]
