# Generated by Django 2.2.6 on 2020-02-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0066_account_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimages',
            name='project_id',
            field=models.IntegerField(default=None),
        ),
    ]
