# Generated by Django 2.2.6 on 2019-11-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191105_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'developer'), (2, 'Technical'), (3, 'admin')], default=2),
            preserve_default=False,
        ),
    ]
