# Generated by Django 2.2.6 on 2019-11-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_type',
        ),
    ]
