# Generated by Django 2.2.6 on 2019-11-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_json_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='category_id',
            new_name='skill_id',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='skills',
            new_name='skill_name',
        ),
        migrations.AddField(
            model_name='skills',
            name='project_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
