# Generated by Django 2.2.6 on 2019-11-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_account_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('skills', models.TextField()),
                ('profile', models.ImageField(upload_to='pictures/')),
                ('coverphoto', models.ImageField(upload_to='pictures/')),
                ('country', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
