# Generated by Django 2.2.6 on 2019-11-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191115_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproject',
            name='route',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
