# Generated by Django 2.2.6 on 2019-11-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191115_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(default=None, max_length=30, null=True)),
                ('project_name', models.CharField(default=None, max_length=300, null=True)),
                ('bid_amount', models.IntegerField()),
                ('user_id', models.IntegerField(default=None, null=True)),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='No_of_bids_for_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(default=None, max_length=30, null=True)),
                ('project_name', models.CharField(default=None, max_length=300, null=True)),
                ('no_of_bid', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updates_at')),
            ],
        ),
    ]
