# Generated by Django 2.2.6 on 2019-11-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_bidproject_no_of_bids_for_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidproject',
            name='no_of_bid',
            field=models.IntegerField(default=None),
        ),
    ]
