# Generated by Django 2.2.6 on 2019-11-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20191106_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
