# Generated by Django 2.2.6 on 2019-11-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20191122_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postproject',
            name='skill1',
        ),
        migrations.RemoveField(
            model_name='postproject',
            name='skill2',
        ),
        migrations.RemoveField(
            model_name='postproject',
            name='skill3',
        ),
        migrations.RemoveField(
            model_name='postproject',
            name='skill4',
        ),
        migrations.RemoveField(
            model_name='postproject',
            name='skills',
        ),
    ]
