# Generated by Django 2.2.6 on 2019-11-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_bidproject_no_of_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidproject',
            name='no_of_bid',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
