# Generated by Django 2.2.6 on 2019-11-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20191106_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userid',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
