# Generated by Django 2.2.6 on 2019-11-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20191118_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('skill_id', models.IntegerField()),
                ('skill_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updates_at')),
            ],
        ),
    ]
