# Generated by Django 2.2.6 on 2019-11-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userprofile_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_freelancer',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
