# Generated by Django 2.2.6 on 2019-11-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_skills_skill_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skill_code',
        ),
        migrations.AddField(
            model_name='const_skills',
            name='skill_code',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
