# Generated by Django 2.2.6 on 2019-11-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_account_is_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_freelancer',
            field=models.IntegerField(default=False),
        ),
    ]
