# Generated by Django 2.2.6 on 2019-11-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_project_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='sub_category_id',
        ),
    ]
