# Generated by Django 2.2.6 on 2019-11-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20191106_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budgetid', models.IntegerField()),
                ('currencyid', models.IntegerField()),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updates_at')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budgettype', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updates_at')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencytype', models.CharField(max_length=30)),
                ('currencysymbol', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updates_at')),
            ],
        ),
    ]
