# Generated by Django 2.2.6 on 2019-11-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_budget_budgettype_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='currencysymbol',
        ),
    ]
