# Generated by Django 2.2.6 on 2019-11-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20191125_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skill_name',
        ),
    ]
