# Generated by Django 2.2.6 on 2019-11-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_currency_currencysymbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='currencysymbol',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
