# Generated by Django 2.2.6 on 2019-11-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_currency_currencysymbol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.RemoveField(
            model_name='postproject',
            name='budgetType',
        ),
        migrations.RemoveField(
            model_name='postproject',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='postproject',
            name='projectbudget',
        ),
        migrations.AddField(
            model_name='postproject',
            name='budgetTypeId',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='postproject',
            name='currencyid',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='postproject',
            name='max',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postproject',
            name='min',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
