# Generated by Django 2.2.6 on 2019-11-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20191107_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postproject',
            old_name='projectname',
            new_name='projecttitle',
        ),
        migrations.AddField(
            model_name='postproject',
            name='categorycode',
            field=models.CharField(default=None, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='postproject',
            name='subcategorycode',
            field=models.CharField(default=None, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='postproject',
            name='max',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='postproject',
            name='min',
            field=models.IntegerField(default=None),
        ),
    ]
