# Generated by Django 2.2.6 on 2019-11-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20191107_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postproject',
            name='max',
        ),
        migrations.RemoveField(
            model_name='postproject',
            name='min',
        ),
        migrations.AlterField(
            model_name='postproject',
            name='budgetTypeId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='postproject',
            name='categorycode',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='postproject',
            name='currencyid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='postproject',
            name='subcategorycode',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
