# Generated by Django 2.2.6 on 2019-11-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20191107_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproject',
            name='categorycode',
            field=models.CharField(default=2, max_length=60, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postproject',
            name='subcategorycode',
            field=models.CharField(default=2, max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
