# Generated by Django 2.2.6 on 2019-11-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20191114_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('profilepic', models.ImageField(upload_to='pictures/')),
                ('current_ongoing_jobs', models.CharField(max_length=40)),
                ('completed_recent_projects', models.CharField(max_length=40)),
                ('recommended_jobs', models.CharField(max_length=40)),
                ('wallet', models.IntegerField()),
                ('feedback_reviews', models.CharField(max_length=40)),
            ],
        ),
    ]
