# Generated by Django 2.2.6 on 2019-11-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(default=None)),
                ('skills', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(default=None)),
                ('subcategoryname', models.CharField(max_length=60)),
                ('subcategorycode', models.CharField(default=None, max_length=60, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='categories',
            name='subcategorycode',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='subcategoryname',
        ),
    ]
