# Generated by Django 2.2.6 on 2019-12-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_hirer_bid_select_project_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirer_bid_select',
            name='hirer_email_id',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
