# Generated by Django 2.2.6 on 2019-12-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20191217_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirer_bid_select',
            name='message',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
