# Generated by Django 2.2.6 on 2019-12-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_hirer_bid_select_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='profile_pic',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='hirer_bid_select',
            name='message',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='kycinfo',
            name='idproofback',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='kycinfo',
            name='idprooffront',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(upload_to=''),
        ),
    ]
